services:
  server:
    build:
      context: ./backend
      target: development
    ports:
      - 8080:8080
    develop:
      watch:
        - action: rebuild
          path: ./backend
    env_file:
      - ./backend/.env
      - path: ./backend/.env.local
        required: false

  client:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    env_file:
      - ./frontend/.env
      - path: ./backend/.env.local
        required: false
    environment:
      WATCHPACK_POLLING: "true"
    depends_on:
      - server
    develop:
      watch:
        - action: sync
          path: ./frontend
          target: /app
          ignore:
            - node_modules/
            - .next/
        - action: rebuild
          path: frontend/package.json